export const STATS_LOADING_JOKE_INTERVAL_MS = 4200;

export const STATS_LOADING_JOKES: string[] = [
    'Calculating the padders...',
    'Wrangling the squirrels...',
    'Counting bags per tick...',
    'Measuring boonball density...',
    'Finding who pressed Stand Your Ground on cooldown...',
    'Converting cloud DPS into actionable data...',
    'Checking if that was a tactical waypoint...',
    'Debating if this was content or karma train...',
    'Sorting comm pings by panic level...',
    'Rebuilding morale after queue map...',
    'Estimating how many times someone said "push now"...',
    'Auditing stealth bombs and coping mechanisms...',
    'Polishing commander tags...',
    'Recharging warclaw batteries...',
    'Calibrating arrow cart trajectories...',
    'Inspecting every suspicious 25 Might stack...',
    'Confirming that was definitely line of sight...',
    'Converting supply into emotional damage...',
    'Filing paperwork for accidental portal science...',
    'Checking if the scout was actually at the camp...',
    'Recounting downs after rally chaos...',
    'Verifying if that was a clean disengage...',
    'Indexing all "I was lagging" reports...',
    'Investigating mysterious downstate heroics...',
    'Comparing pirate ship drift angles...',
    'Sharpening stab and aegis statistics...',
    'Reassembling fragments of the frontline...',
    'Syncing golem benchmarks with reality...',
    'Separating boon support from good intentions...',
    'Mapping dodge rolls to probable outcomes...',
    'Estimating projectile hate levels...',
    'Checking if that pull was legal in Tyria...',
    'Refining siege placement feng shui...',
    'Counting how many times someone tab-targeted a yak...',
    'Calculating average confidence before first push...',
    'Locating the exact second the flank became a wipe...',
    'Comparing map chat callouts to actual events...',
    'Quantifying chaos per minute...',
    'Measuring value generated per warclaw leap...',
    'Compiling a list of regrettable pushes...',
    'Normalizing boonstrip greed indexes...',
    'Calculating morale damage from random treb hits...',
    'Determining if that was bait or just optimism...',
    'Reviewing staff marks for artistic merit...',
    'Filtering out accidental auto-attacks...',
    'Balancing boon uptime against personal style...',
    'Detecting overextended hero moments...',
    'Translating "small scale" into squad math...',
    'Auditing cooldowns that definitely were up...',
    'Reconstructing the timeline of panic dodges...',
    'Classifying enemy blobs by menace level...',
    'Estimating blob size using advanced guesswork...',
    'Checking if that target caller was cooking...',
    'Tracking unexplained boon disappearance events...',
    'Estimating supply spent on vibes...',
    'Computing legal liability for fake pushes...',
    'Running quality assurance on disengage paths...',
    'Cross-referencing comms with battlefield physics...',
    'Investigating unexpected trebuchet diplomacy...',
    'Calculating catapult confidence intervals...',
    'Indexing all perfectly timed downs...',
    'Looking for value in every meteor shower...',
    'Reviewing blink routes for workplace safety...',
    'Tallying questionable stealth reveals...',
    'Checking if "outnumbered" was emotional or literal...',
    'Simulating three alternate timelines where that push worked...',
    'Replaying spike windows at 300% copium...',
    'Auditing cloud behavior for suspicious circles...',
    'Estimating commander patience remaining...',
    'Generating highly scientific post-fight excuses...',
    'Reconciling wipes with "we almost had them"...',
    'Counting blast finishers that were definitely planned...',
    'Searching for that one lost guardian...',
    'Re-evaluating life choices after supply trap wipes...',
    'Determining if the enemy comp was legal...',
    'Computing rally probability under emotional pressure...',
    'Measuring commander sigh frequency...',
    'Estimating fear uptime on enemy supports...',
    'Converting siege splash into modern art...',
    'Validating "I had no stab" claims...',
    'Checking if someone dropped food this fight...',
    'Reviewing boonstrip logs for spicy plays...',
    'Locating all unexplained facechecks...',
    'Mapping meteor showers to keyboard dents...',
    'Estimating if that was one pull too many...',
    'Calculating squad cohesion after one bad port...',
    'Cross-checking focus calls with target health...',
    'Ranking leaps by dramatic effect...',
    'Estimating cleanse demand during bomb windows...',
    'Inspecting downstate rotations for compliance...',
    'Converting panic into clean spreadsheets...',
    'Testing the structural integrity of the backline...',
    'Counting shades, wells, and hard feelings...',
    'Measuring guardian bubble aura intensity...',
    'Investigating anomalous boons at 03:00...',
    'Comparing stomps attempted vs stomps completed...',
    'Tagging all accidental hero pushes...',
    'Calculating dodge tax across the squad...',
    'Evaluating water field return on investment...',
    'Auditing projectile denial and emotional denial...',
    'Checking if that portal had a permit...',
    'Tracing all failed flanks to their origin story...',
    'Calculating post-wipe regroup half-life...',
    'Estimating average melee courage per second...',
    'Correlating spikes with enthusiastic voice comms...',
    'Checking if that bomb was crisp or crunchy...',
    'Normalizing data for "just one more fight"...',
    'Reviewing stealth openers for dramatic timing...',
    'Estimating if your rev was in Narnia...',
    'Counting banner placements that inspired confidence...',
    'Investigating unexplained quickness disappearances...',
    'Running anti-tilt calibration routines...',
    'Computing enemy respect levels in real time...',
    'Calculating firebrand lecture throughput...',
    'Identifying legal targets in the cloud...',
    'Reviewing all moments of tactical hesitation...',
    'Calibrating go-next probability...',
    'Collecting witness statements from downstate...',
    'Measuring map queue trauma carryover...',
    'Checking for unauthorized 1v20 attempts...',
    'Estimating value from last-second bubble drops...',
    'Reviewing supply spent on motivational siege...',
    'Converting spike data into confidence...',
    'Detecting statistically significant overcommit...',
    'Tracing every disengage to a good intention...',
    'Profiling boonrip efficiency by chaos level...',
    'Computing blame distribution matrices...',
    'Auditing cleanse budgets and debt...',
    'Finding the exact frame someone yelled "stab"...',
    'Estimating collateral damage from whirlwinds...',
    'Calculating pirate ship shell dispersion...',
    'Reviewing shockwave etiquette violations...',
    'Identifying downstate heroes and villains...',
    'Measuring line-push conviction scores...',
    'Checking if "full send" had a backup plan...',
    'Correlating pings with sprint key usage...',
    'Mapping boon downtime to emotional downtime...',
    'Counting moments where everyone was one dodge late...',
    'Computing support appreciation metrics...',
    'Evaluating sustain versus stubbornness...',
    'Compiling clips for the tactical blooper reel...',
    'Estimating fog of war plus fog of memory...',
    'Scanning for illegal melee greed...',
    'Converting "nice try" into hard numbers...',
    'Tracking stealth entry and dramatic exits...',
    'Reviewing hammer train ticket validation...',
    'Finding all cases of accidental overextension...',
    'Measuring stability confidence intervals...',
    'Estimating if that was a bait ping...',
    'Calculating siege engineer overtime...',
];

export const shuffled = <T,>(values: T[]): T[] => {
    const out = [...values];
    for (let i = out.length - 1; i > 0; i -= 1) {
        const j = Math.floor(Math.random() * (i + 1));
        [out[i], out[j]] = [out[j], out[i]];
    }
    return out;
};
