import type { CommanderFightData } from '../../../../shared/commanderTypes';

export function baseFight(overrides: Partial<CommanderFightData> = {}): CommanderFightData {
  return {
    fightId: 'x',
    map: 'Test',
    startedAt: 0,
    duration: 60,
    matchup: {
      squadCount: 25,
      alliesCount: 0,
      enemyCount: 50,
      enemyPeak: 50,
      effectiveRatio: 0.5,
      timeOutnumberedSec: 0,
      enemyComp: [],
      enemyByTeam: [],
      squadColor: null,
      inTagBubbleAtEngage: 25,
    },
    survival: {
      firstSquadDeath: null,
      firstSupportDeath: null,
      squadAliveAtEnd: 25,
      squadTotal: 25,
      rallyRate: 0,
      rallies: 0,
      downs: 0,
      avgTimeDownedSec: 0,
    },
    burst: {
      worst3sIncoming: 0,
      worst3sIncomingTSec: 0,
      inHealRatioAtSpike: 0,
      healAtSpike: 0,
      bombWindowCount: 0,
      bombWindows: [],
      downsInWorst3s: 0,
      stabUptimeInSpike: 0,
    },
    cohesion: {
      avgDistFromTag: 400,
      timeSpread900PlusSec: 0,
      avgDistAtDeath: 400,
      peakSpreadStdev: 0,
      peakSpreadStdevTSec: 0,
      stragglersAtBomb: 0,
    },
    sustain: {
      cleansesApplied: 0,
      conditionsTaken: 0,
      stripsLanded: 0,
      stripsReceived: 0,
      stabThroughBombs: 0,
      resistanceAtBurst: 0,
      aegisAtBurst: 0,
    },
    engage: {
      squadHpAtEngage: 1,
      keyCdsUsed0to10s: 0,
      preEngageDowns: 0,
      stab0to10s: 0,
      dodgeStarvation: 'low',
    },
    outcome: {
      kills: 0,
      squadDeaths: 0,
      allyDeaths: 0,
      netTrade: 0,
      damageOut: 0,
      damageIn: 0,
      damageOutInRatio: 0,
    },
    series: {
      incomingDps: [],
      healingThroughput: [],
      stabUptime: [],
      spreadStdev: [],
      deathsTimeline: [],
    },
    verdictChips: [],
    ...overrides,
  };
}
